#!/bin/bash

echo "🔄 Tüm view dosyalarını güncelliyorum..."

# Common replacements
declare -A replacements=(
    ["Text(\"İptal\")"]="Text(L.cancel)"
    ["Text(\"Tamam\")"]="Text(L.ok)"
    ["Text(\"Kaydet\")"]="Text(L.save)"
    ["Text(\"Sil\")"]="Text(L.delete)"
    ["Text(\"Kapat\")"]="Text(L.close)"
    ["Text(\"Geri\")"]="Text(L.back)"
    ["Text(\"İleri\")"]="Text(L.next)"
    ["Text(\"Atla\")"]="Text(L.skip)"
    ["Text(\"Başla\")"]="Text(L.start)"
    ["Text(\"Oluştur\")"]="Text(L.create)"
    ["Text(\"Yükleniyor...\")"]="Text(L.loading)"
    ["Text(\"Yeni\")"]="Text(L.new)"
    ["Text(\"Popüler\")"]="Text(L.popular)"
    ["Text(\"Sınırsız\")"]="Text(L.unlimited)"
    ["Text(\"Premium\")"]="Text(L.premium)"
    ["Text(\"Ana Sayfa\")"]="Text(L.home)"
    ["Text(\"Kütüphane\")"]="Text(L.library)"
    ["Text(\"Ayarlar\")"]="Text(L.settings)"
    ["Text(\"Günlük\")"]="Text(L.daily)"
    ["Text(\"Görselli Hikaye\")"]="Text(L.illustratedStory)"
    ["Text(\"Metin Hikaye\")"]="Text(L.textStory)"
    ["Text(\"Günlük Hikaye\")"]="Text(L.dailyStory)"
    ["Text(\"Hikaye Oluştur\")"]="Text(L.createStory)"
    ["Text(\"Çocuğun Adı\")"]="Text(L.childName)"
    ["Text(\"Yaş\")"]="Text(L.age)"
    ["Text(\"Cinsiyet\")"]="Text(L.gender)"
    ["Text(\"Erkek\")"]="Text(L.boy)"
    ["Text(\"Kız\")"]="Text(L.girl)"
    ["Text(\"Hikaye Teması\")"]="Text(L.storyTheme)"
    ["Text(\"Tema Seç\")"]="Text(L.selectTheme)"
    ["Text(\"Henüz Hikaye Yok\")"]="Text(L.noStoriesInLibrary)"
    ["Text(\"Hikayeyi Sil\")"]="Text(L.deleteStory)"
    ["Text(\"Profil\")"]="Text(L.profile)"
    ["Text(\"Dil\")"]="Text(L.language)"
    ["Text(\"Bildirimler\")"]="Text(L.notifications)"
    ["Text(\"Hakkında\")"]="Text(L.about)"
    ["Text(\"Önceki\")"]="Text(L.previous)"
    ["Text(\"Sonraki\")"]="Text(L.nextPage)"
    ["Text(\"Okuma İpucu\")"]="Text(L.readingTip)"
    ["Text(\"Hikaye Kulübü\")"]="Text(L.storyClub)"
    ["Text(\"Kulübe Katıl\")"]="Text(L.joinClub)"
    ["Text(\"EN POPÜLER\")"]="Text(L.mostPopular)"
    ["Text(\"Ücretsiz Paket\")"]="Text(L.freePackage)"
    ["Text(\"İsim\")"]="Text(L.name)"
    ["Text(\"Kategoriler\")"]="Text(L.categories)"
    ["Text(\"Menü\")"]="Text(L.menu)"
    ["Text(\"Yükselt\")"]="Text(L.upgrade)"
    ["Text(\"Okundu\")"]="Text(L.read)"
    ["Text(\"Premium Üye\")"]="Text(L.premium)"
    ["Text(\"Ücretsiz Deneme\")"]="Text(L.freeTrial)"
    ["Text(\"Kulüp Üyeliği Gerekli\")"]="Text(L.clubMembershipRequired)"
    ["Text(\"Günün Hikayesi\")"]="Text(L.dailyStory)"
    ["Text(\"Hikayenin Öğretisi\")"]="Text(L.storyLesson)"
    ["Text(\"Önizleme\")"]="Text(L.preview)"
    ["Text(\"Yazı Boyutu\")"]="Text(L.textSize)"
    ["Text(\"Okuma Teması\")"]="Text(L.readingTheme)"
    ["Text(\"Satır Aralığı\")"]="Text(L.lineSpacing)"
    ["Text(\"Otomatik Oynat\")"]="Text(L.autoPlay)"
    ["Text(\"Yüksek Kontrast Aktif\")"]="Text(L.highContrastActive)"
    ["Text(\"Temel Bilgiler\")"]="Text(L.basicInfo)"
    ["Text(\"Çocuk Bilgileri\")"]="Text(L.childInfo)"
    ["Text(\"Hikaye Kategorisi\")"]="Text(L.storyCategory)"
)

# Apply replacements to all view files
for file in MagicPaper/Views/*.swift; do
    echo "📝 Güncelleniyor: $file"
    for search in "${!replacements[@]}"; do
        replacement="${replacements[$search]}"
        # Use perl for better regex support
        perl -i -pe "s/\Q$search\E/$replacement/g" "$file"
    done
done

echo "✅ Tüm dosyalar güncellendi!"
echo ""
echo "Sonraki adım: Build et ve test et"
